title: Noga Levinson
tagline: Electrochemistry - Organic electronics - Advanced functional materials
description: MSc Chem at the Weizmann Institute - electrochromic thin films, photo-electrochromic devices, DSSCs, graphene, Cu(111)
theme: minima
logo: /assets/avatar.png
author:
  name: Noga Levinson
  email: your.email@example.com
  location: Israel
  affiliations:
    - Weizmann Institute of Science
  roles:
    - Electrochemistry
    - Organic electronics
    - Materials science
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/yourhandle" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/yourhandle" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=XXXX" }
    - { platform: orcid, user_url: "https://orcid.org/XXXX" }
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  projects:
    output: true
  publications:
    output: true
defaults:
  - scope: { path: "", type: "projects" }
    values: { layout: page }
  - scope: { path: "", type: "publications" }
    values: { layout: page }
